#:kivy 1.0
<FirstScreen>:
    GridLayout:
        cols: 1
        padding:12
        spacing:8
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_input
            size_hint_y: 0.1
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.set_image()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'